apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: iy91q2tnf-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:f6a2508feb4460f7ceb1029cb5eafd4ed5e2ee45@sha256:4d02affacf5583cd6052757584fd1728a8ca0b2de258445c15b8cefabd226464
          name: container-image
